# Generated by Django 5.0.6 on 2024-06-30 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('activo', models.IntegerField()),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
            ],
        ),
    ]
