# Generated by Django 5.0.6 on 2024-06-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='portada',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
