# Generated by Django 5.0.6 on 2024-07-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='rut',
            field=models.ForeignKey(db_column='rut', default=34843458734, on_delete=django.db.models.deletion.PROTECT, to='tienda.usuario'),
            preserve_default=False,
        ),
    ]
